typography_spectrum: 0.9349765055812895
color:
  brandStrength: 0.3218544367700815
  lightness: 0.022157976171001792
  saturation: 0.5569336747284979
  rhythmicContrast: 0.46376154478639364
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.6080400655046105
name: surreality
navigation:
  - name: 'The world is yours, deer'
    id: 2dc11ed7-0fcd-49a4-bb3c-c6b730f04650
    type: content
  - name: test external link
    url: 'http://crescogames.x10hosting.com/'
    type: external
title: Our Weird and Wonderful World
description: ''
